service: legal-backend

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'staging'}
  region: ap-south-1
  iamManagedPolicies:
  - 'arn:aws:iam::aws:policy/AmazonSQSFullAccess'
  iamRoleStatements:
  - Effect: Allow
    Action:
      - "s3:*"
    Resource: 
      - { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ]]}
      - "arn:aws:s3:::legal-user-files/*"
  environment:
    APP_ENV: ${self:provider.stage}
    DB_USERNAME: ${ssm:/${self:provider.stage}/internal/legal/username}
    DB_PASSWORD: ${ssm:/${self:provider.stage}/internal/legal/password}
    DB_NAME: ${ssm:/${self:provider.stage}/internal/legal/dbname}
    DB_HOST: ${ssm:/${self:provider.stage}/internal/legal/host}
    MONGO_URI: ${ssm:/${self:provider.stage}/internal/mongo/dburi}
    APPWRITE_PROJECT_ID : ${ssm:/${self:provider.stage}/internal/apwrite/projectid}
    APPWRITE_ENDPOINT : ${ssm:/${self:provider.stage}/internal/apwrite/endpoint}
    APPWRITE_SERVER_API_KEY : ${ssm:/${self:provider.stage}/internal/apwrite/apikey}
    RAZORPAY_WEBHOOK_SECRET : ${ssm:/${self:provider.stage}/internal/razorpay/webhook/secret}
    V1_API_KEY :  ${ssm:/${self:provider.stage}/internal/v1/apikey}
functions:
  main:
    handler: index.handler
    memorySize: 512
    timeout: 30
    events:
      - http:
          method: ANY
          path:  /
      - http:
          method: ANY 
          path: /{proxy+}
  razorpayEvents:
    handler: razorpayEvents.handler
    memorySize: 512
    timeout: 30
    events:
      - http:
          method: ANY
          path:  /webhooks/razorpay
  messageQueue:
    handler: sqs.handler
    memorySize: 512
    timeout: 900
    events:
      - sqs: 
          arn: arn:aws:sqs:ap-south-1:865096565437:legal-${self:provider.stage}.fifo
          
      
plugins:
  - serverless-prune-plugin